name: Issue Credential

on: workflow_dispatch

jobs:
  issue-credential:
    runs-on: ubuntu-latest
    name: Recent Activity
    outputs:
      json: ${{ steps.issue-credential.outputs.json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Issue Credential
        uses: ./
        id: issue-credential
