name: Issue Credential

on: workflow_dispatch

jobs:
  issue-credential:
    runs-on: ubuntu-latest
    name: Issue Credential
    outputs:
      json: ${{ steps.issue-credential.outputs.json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Issue Credential
        uses: ./
        id: issue-credential
        with:
          did: ${{ secrets.ORGANIZATION_DID_WEB }}
          tokenEndpoint: ${{ secrets.TOKEN_ENDPOINT }}
          tokenAudience: ${{ secrets.TOKEN_AUDIENCE }}
          apiBaseUrl: ${{ secrets.API_BASE_URL }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
      - name: Review the results
        run: |-
          echo '${{ steps.issue-credential.outputs.json }}' >> verifiable-credential.json
      - name: Upload the issued credential as a workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: issued-verifiable-credential
          path: verifiable-credential.json
